# coding: utf-8

"""
    CartoVista REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class DataTableJoinParameter(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'data_table_source_identifier': 'str',
        'data_table_target_column_identifier': 'str',
        'data_table_source_column_identifier': 'str'
    }

    attribute_map = {
        'data_table_source_identifier': 'dataTableSourceIdentifier',
        'data_table_target_column_identifier': 'dataTableTargetColumnIdentifier',
        'data_table_source_column_identifier': 'dataTableSourceColumnIdentifier'
    }

    def __init__(self, data_table_source_identifier=None, data_table_target_column_identifier=None, data_table_source_column_identifier=None):  # noqa: E501
        """DataTableJoinParameter - a model defined in Swagger"""  # noqa: E501
        self._data_table_source_identifier = None
        self._data_table_target_column_identifier = None
        self._data_table_source_column_identifier = None
        self.discriminator = None
        if data_table_source_identifier is not None:
            self.data_table_source_identifier = data_table_source_identifier
        if data_table_target_column_identifier is not None:
            self.data_table_target_column_identifier = data_table_target_column_identifier
        if data_table_source_column_identifier is not None:
            self.data_table_source_column_identifier = data_table_source_column_identifier

    @property
    def data_table_source_identifier(self):
        """Gets the data_table_source_identifier of this DataTableJoinParameter.  # noqa: E501


        :return: The data_table_source_identifier of this DataTableJoinParameter.  # noqa: E501
        :rtype: str
        """
        return self._data_table_source_identifier

    @data_table_source_identifier.setter
    def data_table_source_identifier(self, data_table_source_identifier):
        """Sets the data_table_source_identifier of this DataTableJoinParameter.


        :param data_table_source_identifier: The data_table_source_identifier of this DataTableJoinParameter.  # noqa: E501
        :type: str
        """

        self._data_table_source_identifier = data_table_source_identifier

    @property
    def data_table_target_column_identifier(self):
        """Gets the data_table_target_column_identifier of this DataTableJoinParameter.  # noqa: E501


        :return: The data_table_target_column_identifier of this DataTableJoinParameter.  # noqa: E501
        :rtype: str
        """
        return self._data_table_target_column_identifier

    @data_table_target_column_identifier.setter
    def data_table_target_column_identifier(self, data_table_target_column_identifier):
        """Sets the data_table_target_column_identifier of this DataTableJoinParameter.


        :param data_table_target_column_identifier: The data_table_target_column_identifier of this DataTableJoinParameter.  # noqa: E501
        :type: str
        """

        self._data_table_target_column_identifier = data_table_target_column_identifier

    @property
    def data_table_source_column_identifier(self):
        """Gets the data_table_source_column_identifier of this DataTableJoinParameter.  # noqa: E501


        :return: The data_table_source_column_identifier of this DataTableJoinParameter.  # noqa: E501
        :rtype: str
        """
        return self._data_table_source_column_identifier

    @data_table_source_column_identifier.setter
    def data_table_source_column_identifier(self, data_table_source_column_identifier):
        """Sets the data_table_source_column_identifier of this DataTableJoinParameter.


        :param data_table_source_column_identifier: The data_table_source_column_identifier of this DataTableJoinParameter.  # noqa: E501
        :type: str
        """

        self._data_table_source_column_identifier = data_table_source_column_identifier

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DataTableJoinParameter, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DataTableJoinParameter):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
