# coding: utf-8

"""
    CartoVista REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class DeleteDataColumnResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'column_id': 'str',
        'did_delete': 'bool',
        'affected_spatial_joins': 'list[SpatialJoinLayerPair]',
        'deleted_spatial_join_table_ids': 'list[str]',
        'has_permission': 'bool',
        'would_delete_spatial_join': 'bool'
    }

    attribute_map = {
        'column_id': 'columnId',
        'did_delete': 'didDelete',
        'affected_spatial_joins': 'affectedSpatialJoins',
        'deleted_spatial_join_table_ids': 'deletedSpatialJoinTableIds',
        'has_permission': 'hasPermission',
        'would_delete_spatial_join': 'wouldDeleteSpatialJoin'
    }

    def __init__(self, column_id=None, did_delete=None, affected_spatial_joins=None, deleted_spatial_join_table_ids=None, has_permission=None, would_delete_spatial_join=None):  # noqa: E501
        """DeleteDataColumnResponse - a model defined in Swagger"""  # noqa: E501
        self._column_id = None
        self._did_delete = None
        self._affected_spatial_joins = None
        self._deleted_spatial_join_table_ids = None
        self._has_permission = None
        self._would_delete_spatial_join = None
        self.discriminator = None
        if column_id is not None:
            self.column_id = column_id
        if did_delete is not None:
            self.did_delete = did_delete
        if affected_spatial_joins is not None:
            self.affected_spatial_joins = affected_spatial_joins
        if deleted_spatial_join_table_ids is not None:
            self.deleted_spatial_join_table_ids = deleted_spatial_join_table_ids
        if has_permission is not None:
            self.has_permission = has_permission
        if would_delete_spatial_join is not None:
            self.would_delete_spatial_join = would_delete_spatial_join

    @property
    def column_id(self):
        """Gets the column_id of this DeleteDataColumnResponse.  # noqa: E501


        :return: The column_id of this DeleteDataColumnResponse.  # noqa: E501
        :rtype: str
        """
        return self._column_id

    @column_id.setter
    def column_id(self, column_id):
        """Sets the column_id of this DeleteDataColumnResponse.


        :param column_id: The column_id of this DeleteDataColumnResponse.  # noqa: E501
        :type: str
        """

        self._column_id = column_id

    @property
    def did_delete(self):
        """Gets the did_delete of this DeleteDataColumnResponse.  # noqa: E501


        :return: The did_delete of this DeleteDataColumnResponse.  # noqa: E501
        :rtype: bool
        """
        return self._did_delete

    @did_delete.setter
    def did_delete(self, did_delete):
        """Sets the did_delete of this DeleteDataColumnResponse.


        :param did_delete: The did_delete of this DeleteDataColumnResponse.  # noqa: E501
        :type: bool
        """

        self._did_delete = did_delete

    @property
    def affected_spatial_joins(self):
        """Gets the affected_spatial_joins of this DeleteDataColumnResponse.  # noqa: E501


        :return: The affected_spatial_joins of this DeleteDataColumnResponse.  # noqa: E501
        :rtype: list[SpatialJoinLayerPair]
        """
        return self._affected_spatial_joins

    @affected_spatial_joins.setter
    def affected_spatial_joins(self, affected_spatial_joins):
        """Sets the affected_spatial_joins of this DeleteDataColumnResponse.


        :param affected_spatial_joins: The affected_spatial_joins of this DeleteDataColumnResponse.  # noqa: E501
        :type: list[SpatialJoinLayerPair]
        """

        self._affected_spatial_joins = affected_spatial_joins

    @property
    def deleted_spatial_join_table_ids(self):
        """Gets the deleted_spatial_join_table_ids of this DeleteDataColumnResponse.  # noqa: E501


        :return: The deleted_spatial_join_table_ids of this DeleteDataColumnResponse.  # noqa: E501
        :rtype: list[str]
        """
        return self._deleted_spatial_join_table_ids

    @deleted_spatial_join_table_ids.setter
    def deleted_spatial_join_table_ids(self, deleted_spatial_join_table_ids):
        """Sets the deleted_spatial_join_table_ids of this DeleteDataColumnResponse.


        :param deleted_spatial_join_table_ids: The deleted_spatial_join_table_ids of this DeleteDataColumnResponse.  # noqa: E501
        :type: list[str]
        """

        self._deleted_spatial_join_table_ids = deleted_spatial_join_table_ids

    @property
    def has_permission(self):
        """Gets the has_permission of this DeleteDataColumnResponse.  # noqa: E501


        :return: The has_permission of this DeleteDataColumnResponse.  # noqa: E501
        :rtype: bool
        """
        return self._has_permission

    @has_permission.setter
    def has_permission(self, has_permission):
        """Sets the has_permission of this DeleteDataColumnResponse.


        :param has_permission: The has_permission of this DeleteDataColumnResponse.  # noqa: E501
        :type: bool
        """

        self._has_permission = has_permission

    @property
    def would_delete_spatial_join(self):
        """Gets the would_delete_spatial_join of this DeleteDataColumnResponse.  # noqa: E501


        :return: The would_delete_spatial_join of this DeleteDataColumnResponse.  # noqa: E501
        :rtype: bool
        """
        return self._would_delete_spatial_join

    @would_delete_spatial_join.setter
    def would_delete_spatial_join(self, would_delete_spatial_join):
        """Sets the would_delete_spatial_join of this DeleteDataColumnResponse.


        :param would_delete_spatial_join: The would_delete_spatial_join of this DeleteDataColumnResponse.  # noqa: E501
        :type: bool
        """

        self._would_delete_spatial_join = would_delete_spatial_join

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DeleteDataColumnResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DeleteDataColumnResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
