# coding: utf-8

"""
    CartoVista REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class MapLibreGridLayerSettings(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'name': 'str',
        'grid_layer_type': 'GridLayerTypeEnum',
        'grid_sources': 'list[MapLibreGridSourceSettings]',
        'settings': 'GridLayerSettings'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'grid_layer_type': 'gridLayerType',
        'grid_sources': 'gridSources',
        'settings': 'settings'
    }

    def __init__(self, id=None, name=None, grid_layer_type=None, grid_sources=None, settings=None):  # noqa: E501
        """MapLibreGridLayerSettings - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._name = None
        self._grid_layer_type = None
        self._grid_sources = None
        self._settings = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if name is not None:
            self.name = name
        if grid_layer_type is not None:
            self.grid_layer_type = grid_layer_type
        if grid_sources is not None:
            self.grid_sources = grid_sources
        if settings is not None:
            self.settings = settings

    @property
    def id(self):
        """Gets the id of this MapLibreGridLayerSettings.  # noqa: E501


        :return: The id of this MapLibreGridLayerSettings.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this MapLibreGridLayerSettings.


        :param id: The id of this MapLibreGridLayerSettings.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this MapLibreGridLayerSettings.  # noqa: E501


        :return: The name of this MapLibreGridLayerSettings.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this MapLibreGridLayerSettings.


        :param name: The name of this MapLibreGridLayerSettings.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def grid_layer_type(self):
        """Gets the grid_layer_type of this MapLibreGridLayerSettings.  # noqa: E501


        :return: The grid_layer_type of this MapLibreGridLayerSettings.  # noqa: E501
        :rtype: GridLayerTypeEnum
        """
        return self._grid_layer_type

    @grid_layer_type.setter
    def grid_layer_type(self, grid_layer_type):
        """Sets the grid_layer_type of this MapLibreGridLayerSettings.


        :param grid_layer_type: The grid_layer_type of this MapLibreGridLayerSettings.  # noqa: E501
        :type: GridLayerTypeEnum
        """

        self._grid_layer_type = grid_layer_type

    @property
    def grid_sources(self):
        """Gets the grid_sources of this MapLibreGridLayerSettings.  # noqa: E501


        :return: The grid_sources of this MapLibreGridLayerSettings.  # noqa: E501
        :rtype: list[MapLibreGridSourceSettings]
        """
        return self._grid_sources

    @grid_sources.setter
    def grid_sources(self, grid_sources):
        """Sets the grid_sources of this MapLibreGridLayerSettings.


        :param grid_sources: The grid_sources of this MapLibreGridLayerSettings.  # noqa: E501
        :type: list[MapLibreGridSourceSettings]
        """

        self._grid_sources = grid_sources

    @property
    def settings(self):
        """Gets the settings of this MapLibreGridLayerSettings.  # noqa: E501


        :return: The settings of this MapLibreGridLayerSettings.  # noqa: E501
        :rtype: GridLayerSettings
        """
        return self._settings

    @settings.setter
    def settings(self, settings):
        """Sets the settings of this MapLibreGridLayerSettings.


        :param settings: The settings of this MapLibreGridLayerSettings.  # noqa: E501
        :type: GridLayerSettings
        """

        self._settings = settings

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(MapLibreGridLayerSettings, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MapLibreGridLayerSettings):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
