# coding: utf-8

"""
    CartoVista REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class MapLibreGridSourceSettings(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'name': 'str',
        'data_type': 'str',
        'units': 'str',
        'decimal_places': 'int',
        'has_no_data_value': 'bool',
        'no_data_value': 'float',
        'possible_classified_values': 'list[int]',
        'src': 'str'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'data_type': 'dataType',
        'units': 'units',
        'decimal_places': 'decimalPlaces',
        'has_no_data_value': 'hasNoDataValue',
        'no_data_value': 'noDataValue',
        'possible_classified_values': 'possibleClassifiedValues',
        'src': 'src'
    }

    def __init__(self, id=None, name=None, data_type=None, units=None, decimal_places=None, has_no_data_value=None, no_data_value=None, possible_classified_values=None, src=None):  # noqa: E501
        """MapLibreGridSourceSettings - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._name = None
        self._data_type = None
        self._units = None
        self._decimal_places = None
        self._has_no_data_value = None
        self._no_data_value = None
        self._possible_classified_values = None
        self._src = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if name is not None:
            self.name = name
        if data_type is not None:
            self.data_type = data_type
        if units is not None:
            self.units = units
        if decimal_places is not None:
            self.decimal_places = decimal_places
        if has_no_data_value is not None:
            self.has_no_data_value = has_no_data_value
        if no_data_value is not None:
            self.no_data_value = no_data_value
        if possible_classified_values is not None:
            self.possible_classified_values = possible_classified_values
        if src is not None:
            self.src = src

    @property
    def id(self):
        """Gets the id of this MapLibreGridSourceSettings.  # noqa: E501


        :return: The id of this MapLibreGridSourceSettings.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this MapLibreGridSourceSettings.


        :param id: The id of this MapLibreGridSourceSettings.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this MapLibreGridSourceSettings.  # noqa: E501


        :return: The name of this MapLibreGridSourceSettings.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this MapLibreGridSourceSettings.


        :param name: The name of this MapLibreGridSourceSettings.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def data_type(self):
        """Gets the data_type of this MapLibreGridSourceSettings.  # noqa: E501


        :return: The data_type of this MapLibreGridSourceSettings.  # noqa: E501
        :rtype: str
        """
        return self._data_type

    @data_type.setter
    def data_type(self, data_type):
        """Sets the data_type of this MapLibreGridSourceSettings.


        :param data_type: The data_type of this MapLibreGridSourceSettings.  # noqa: E501
        :type: str
        """

        self._data_type = data_type

    @property
    def units(self):
        """Gets the units of this MapLibreGridSourceSettings.  # noqa: E501


        :return: The units of this MapLibreGridSourceSettings.  # noqa: E501
        :rtype: str
        """
        return self._units

    @units.setter
    def units(self, units):
        """Sets the units of this MapLibreGridSourceSettings.


        :param units: The units of this MapLibreGridSourceSettings.  # noqa: E501
        :type: str
        """

        self._units = units

    @property
    def decimal_places(self):
        """Gets the decimal_places of this MapLibreGridSourceSettings.  # noqa: E501


        :return: The decimal_places of this MapLibreGridSourceSettings.  # noqa: E501
        :rtype: int
        """
        return self._decimal_places

    @decimal_places.setter
    def decimal_places(self, decimal_places):
        """Sets the decimal_places of this MapLibreGridSourceSettings.


        :param decimal_places: The decimal_places of this MapLibreGridSourceSettings.  # noqa: E501
        :type: int
        """

        self._decimal_places = decimal_places

    @property
    def has_no_data_value(self):
        """Gets the has_no_data_value of this MapLibreGridSourceSettings.  # noqa: E501


        :return: The has_no_data_value of this MapLibreGridSourceSettings.  # noqa: E501
        :rtype: bool
        """
        return self._has_no_data_value

    @has_no_data_value.setter
    def has_no_data_value(self, has_no_data_value):
        """Sets the has_no_data_value of this MapLibreGridSourceSettings.


        :param has_no_data_value: The has_no_data_value of this MapLibreGridSourceSettings.  # noqa: E501
        :type: bool
        """

        self._has_no_data_value = has_no_data_value

    @property
    def no_data_value(self):
        """Gets the no_data_value of this MapLibreGridSourceSettings.  # noqa: E501


        :return: The no_data_value of this MapLibreGridSourceSettings.  # noqa: E501
        :rtype: float
        """
        return self._no_data_value

    @no_data_value.setter
    def no_data_value(self, no_data_value):
        """Sets the no_data_value of this MapLibreGridSourceSettings.


        :param no_data_value: The no_data_value of this MapLibreGridSourceSettings.  # noqa: E501
        :type: float
        """

        self._no_data_value = no_data_value

    @property
    def possible_classified_values(self):
        """Gets the possible_classified_values of this MapLibreGridSourceSettings.  # noqa: E501


        :return: The possible_classified_values of this MapLibreGridSourceSettings.  # noqa: E501
        :rtype: list[int]
        """
        return self._possible_classified_values

    @possible_classified_values.setter
    def possible_classified_values(self, possible_classified_values):
        """Sets the possible_classified_values of this MapLibreGridSourceSettings.


        :param possible_classified_values: The possible_classified_values of this MapLibreGridSourceSettings.  # noqa: E501
        :type: list[int]
        """

        self._possible_classified_values = possible_classified_values

    @property
    def src(self):
        """Gets the src of this MapLibreGridSourceSettings.  # noqa: E501


        :return: The src of this MapLibreGridSourceSettings.  # noqa: E501
        :rtype: str
        """
        return self._src

    @src.setter
    def src(self, src):
        """Sets the src of this MapLibreGridSourceSettings.


        :param src: The src of this MapLibreGridSourceSettings.  # noqa: E501
        :type: str
        """

        self._src = src

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(MapLibreGridSourceSettings, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MapLibreGridSourceSettings):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
