# coding: utf-8

"""
    CartoVista REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Plugin(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'unique_identifier': 'str',
        'name': 'str',
        'url': 'str',
        'logo_icon': 'str',
        'date_created': 'datetime',
        'date_modified': 'datetime',
        'tenant_id': 'str'
    }

    attribute_map = {
        'id': 'id',
        'unique_identifier': 'uniqueIdentifier',
        'name': 'name',
        'url': 'url',
        'logo_icon': 'logoIcon',
        'date_created': 'dateCreated',
        'date_modified': 'dateModified',
        'tenant_id': 'tenantId'
    }

    def __init__(self, id=None, unique_identifier=None, name=None, url=None, logo_icon=None, date_created=None, date_modified=None, tenant_id=None):  # noqa: E501
        """Plugin - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._unique_identifier = None
        self._name = None
        self._url = None
        self._logo_icon = None
        self._date_created = None
        self._date_modified = None
        self._tenant_id = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if unique_identifier is not None:
            self.unique_identifier = unique_identifier
        if name is not None:
            self.name = name
        if url is not None:
            self.url = url
        if logo_icon is not None:
            self.logo_icon = logo_icon
        if date_created is not None:
            self.date_created = date_created
        if date_modified is not None:
            self.date_modified = date_modified
        if tenant_id is not None:
            self.tenant_id = tenant_id

    @property
    def id(self):
        """Gets the id of this Plugin.  # noqa: E501


        :return: The id of this Plugin.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Plugin.


        :param id: The id of this Plugin.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def unique_identifier(self):
        """Gets the unique_identifier of this Plugin.  # noqa: E501


        :return: The unique_identifier of this Plugin.  # noqa: E501
        :rtype: str
        """
        return self._unique_identifier

    @unique_identifier.setter
    def unique_identifier(self, unique_identifier):
        """Sets the unique_identifier of this Plugin.


        :param unique_identifier: The unique_identifier of this Plugin.  # noqa: E501
        :type: str
        """

        self._unique_identifier = unique_identifier

    @property
    def name(self):
        """Gets the name of this Plugin.  # noqa: E501


        :return: The name of this Plugin.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Plugin.


        :param name: The name of this Plugin.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def url(self):
        """Gets the url of this Plugin.  # noqa: E501


        :return: The url of this Plugin.  # noqa: E501
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url):
        """Sets the url of this Plugin.


        :param url: The url of this Plugin.  # noqa: E501
        :type: str
        """

        self._url = url

    @property
    def logo_icon(self):
        """Gets the logo_icon of this Plugin.  # noqa: E501


        :return: The logo_icon of this Plugin.  # noqa: E501
        :rtype: str
        """
        return self._logo_icon

    @logo_icon.setter
    def logo_icon(self, logo_icon):
        """Sets the logo_icon of this Plugin.


        :param logo_icon: The logo_icon of this Plugin.  # noqa: E501
        :type: str
        """

        self._logo_icon = logo_icon

    @property
    def date_created(self):
        """Gets the date_created of this Plugin.  # noqa: E501


        :return: The date_created of this Plugin.  # noqa: E501
        :rtype: datetime
        """
        return self._date_created

    @date_created.setter
    def date_created(self, date_created):
        """Sets the date_created of this Plugin.


        :param date_created: The date_created of this Plugin.  # noqa: E501
        :type: datetime
        """

        self._date_created = date_created

    @property
    def date_modified(self):
        """Gets the date_modified of this Plugin.  # noqa: E501


        :return: The date_modified of this Plugin.  # noqa: E501
        :rtype: datetime
        """
        return self._date_modified

    @date_modified.setter
    def date_modified(self, date_modified):
        """Sets the date_modified of this Plugin.


        :param date_modified: The date_modified of this Plugin.  # noqa: E501
        :type: datetime
        """

        self._date_modified = date_modified

    @property
    def tenant_id(self):
        """Gets the tenant_id of this Plugin.  # noqa: E501


        :return: The tenant_id of this Plugin.  # noqa: E501
        :rtype: str
        """
        return self._tenant_id

    @tenant_id.setter
    def tenant_id(self, tenant_id):
        """Sets the tenant_id of this Plugin.


        :param tenant_id: The tenant_id of this Plugin.  # noqa: E501
        :type: str
        """

        self._tenant_id = tenant_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Plugin, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Plugin):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
