# coding: utf-8

"""
    CartoVista REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class SpatialJoinColumnAggregations(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'column_id': 'str',
        'aggregation_types': 'list[AggregationType]'
    }

    attribute_map = {
        'column_id': 'columnId',
        'aggregation_types': 'aggregationTypes'
    }

    def __init__(self, column_id=None, aggregation_types=None):  # noqa: E501
        """SpatialJoinColumnAggregations - a model defined in Swagger"""  # noqa: E501
        self._column_id = None
        self._aggregation_types = None
        self.discriminator = None
        if column_id is not None:
            self.column_id = column_id
        if aggregation_types is not None:
            self.aggregation_types = aggregation_types

    @property
    def column_id(self):
        """Gets the column_id of this SpatialJoinColumnAggregations.  # noqa: E501


        :return: The column_id of this SpatialJoinColumnAggregations.  # noqa: E501
        :rtype: str
        """
        return self._column_id

    @column_id.setter
    def column_id(self, column_id):
        """Sets the column_id of this SpatialJoinColumnAggregations.


        :param column_id: The column_id of this SpatialJoinColumnAggregations.  # noqa: E501
        :type: str
        """

        self._column_id = column_id

    @property
    def aggregation_types(self):
        """Gets the aggregation_types of this SpatialJoinColumnAggregations.  # noqa: E501


        :return: The aggregation_types of this SpatialJoinColumnAggregations.  # noqa: E501
        :rtype: list[AggregationType]
        """
        return self._aggregation_types

    @aggregation_types.setter
    def aggregation_types(self, aggregation_types):
        """Sets the aggregation_types of this SpatialJoinColumnAggregations.


        :param aggregation_types: The aggregation_types of this SpatialJoinColumnAggregations.  # noqa: E501
        :type: list[AggregationType]
        """

        self._aggregation_types = aggregation_types

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SpatialJoinColumnAggregations, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SpatialJoinColumnAggregations):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
