# coding: utf-8

"""
    CartoVista REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class TerritoryUpdateConflictResolutions(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'capacity': 'int',
        'count': 'int',
        'item': 'TerritoryUpdateConflictResolution',
        'items': 'list[TerritoryUpdateConflictResolution]',
        'size': 'int',
        'version': 'int'
    }

    attribute_map = {
        'capacity': 'Capacity',
        'count': 'Count',
        'item': 'Item',
        'items': '_items',
        'size': '_size',
        'version': '_version'
    }

    def __init__(self, capacity=None, count=None, item=None, items=None, size=None, version=None):  # noqa: E501
        """TerritoryUpdateConflictResolutions - a model defined in Swagger"""  # noqa: E501
        self._capacity = None
        self._count = None
        self._item = None
        self._items = None
        self._size = None
        self._version = None
        self.discriminator = None
        if capacity is not None:
            self.capacity = capacity
        if count is not None:
            self.count = count
        if item is not None:
            self.item = item
        if items is not None:
            self.items = items
        if size is not None:
            self.size = size
        if version is not None:
            self.version = version

    @property
    def capacity(self):
        """Gets the capacity of this TerritoryUpdateConflictResolutions.  # noqa: E501


        :return: The capacity of this TerritoryUpdateConflictResolutions.  # noqa: E501
        :rtype: int
        """
        return self._capacity

    @capacity.setter
    def capacity(self, capacity):
        """Sets the capacity of this TerritoryUpdateConflictResolutions.


        :param capacity: The capacity of this TerritoryUpdateConflictResolutions.  # noqa: E501
        :type: int
        """

        self._capacity = capacity

    @property
    def count(self):
        """Gets the count of this TerritoryUpdateConflictResolutions.  # noqa: E501


        :return: The count of this TerritoryUpdateConflictResolutions.  # noqa: E501
        :rtype: int
        """
        return self._count

    @count.setter
    def count(self, count):
        """Sets the count of this TerritoryUpdateConflictResolutions.


        :param count: The count of this TerritoryUpdateConflictResolutions.  # noqa: E501
        :type: int
        """

        self._count = count

    @property
    def item(self):
        """Gets the item of this TerritoryUpdateConflictResolutions.  # noqa: E501


        :return: The item of this TerritoryUpdateConflictResolutions.  # noqa: E501
        :rtype: TerritoryUpdateConflictResolution
        """
        return self._item

    @item.setter
    def item(self, item):
        """Sets the item of this TerritoryUpdateConflictResolutions.


        :param item: The item of this TerritoryUpdateConflictResolutions.  # noqa: E501
        :type: TerritoryUpdateConflictResolution
        """

        self._item = item

    @property
    def items(self):
        """Gets the items of this TerritoryUpdateConflictResolutions.  # noqa: E501


        :return: The items of this TerritoryUpdateConflictResolutions.  # noqa: E501
        :rtype: list[TerritoryUpdateConflictResolution]
        """
        return self._items

    @items.setter
    def items(self, items):
        """Sets the items of this TerritoryUpdateConflictResolutions.


        :param items: The items of this TerritoryUpdateConflictResolutions.  # noqa: E501
        :type: list[TerritoryUpdateConflictResolution]
        """

        self._items = items

    @property
    def size(self):
        """Gets the size of this TerritoryUpdateConflictResolutions.  # noqa: E501


        :return: The size of this TerritoryUpdateConflictResolutions.  # noqa: E501
        :rtype: int
        """
        return self._size

    @size.setter
    def size(self, size):
        """Sets the size of this TerritoryUpdateConflictResolutions.


        :param size: The size of this TerritoryUpdateConflictResolutions.  # noqa: E501
        :type: int
        """

        self._size = size

    @property
    def version(self):
        """Gets the version of this TerritoryUpdateConflictResolutions.  # noqa: E501


        :return: The version of this TerritoryUpdateConflictResolutions.  # noqa: E501
        :rtype: int
        """
        return self._version

    @version.setter
    def version(self, version):
        """Sets the version of this TerritoryUpdateConflictResolutions.


        :param version: The version of this TerritoryUpdateConflictResolutions.  # noqa: E501
        :type: int
        """

        self._version = version

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TerritoryUpdateConflictResolutions, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TerritoryUpdateConflictResolutions):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
