# coding: utf-8

"""
    CartoVista REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class TerritoryUpdateConflictResolution(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'pos_id': 'str',
        'keep_blocks': 'bool'
    }

    attribute_map = {
        'pos_id': 'posId',
        'keep_blocks': 'keepBlocks'
    }

    def __init__(self, pos_id=None, keep_blocks=None):  # noqa: E501
        """TerritoryUpdateConflictResolution - a model defined in Swagger"""  # noqa: E501
        self._pos_id = None
        self._keep_blocks = None
        self.discriminator = None
        if pos_id is not None:
            self.pos_id = pos_id
        if keep_blocks is not None:
            self.keep_blocks = keep_blocks

    @property
    def pos_id(self):
        """Gets the pos_id of this TerritoryUpdateConflictResolution.  # noqa: E501


        :return: The pos_id of this TerritoryUpdateConflictResolution.  # noqa: E501
        :rtype: str
        """
        return self._pos_id

    @pos_id.setter
    def pos_id(self, pos_id):
        """Sets the pos_id of this TerritoryUpdateConflictResolution.


        :param pos_id: The pos_id of this TerritoryUpdateConflictResolution.  # noqa: E501
        :type: str
        """

        self._pos_id = pos_id

    @property
    def keep_blocks(self):
        """Gets the keep_blocks of this TerritoryUpdateConflictResolution.  # noqa: E501


        :return: The keep_blocks of this TerritoryUpdateConflictResolution.  # noqa: E501
        :rtype: bool
        """
        return self._keep_blocks

    @keep_blocks.setter
    def keep_blocks(self, keep_blocks):
        """Sets the keep_blocks of this TerritoryUpdateConflictResolution.


        :param keep_blocks: The keep_blocks of this TerritoryUpdateConflictResolution.  # noqa: E501
        :type: bool
        """

        self._keep_blocks = keep_blocks

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TerritoryUpdateConflictResolution, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TerritoryUpdateConflictResolution):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
