# coding: utf-8

"""
    CartoVista REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class TerritoryStatusUpdateResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'scenario_id': 'str',
        'pos_id': 'str',
        'exclusive_zone_id': 'int',
        'is_implantation_block_exclusive': 'bool',
        'did_perform_update': 'bool',
        'conflicts': 'TerritoryUpdateConflicts',
        'changes_to_other_territories': 'ChangesToTerritories',
        'status': 'TerritoryStatusEnum',
        'pta_zone_id': 'int',
        'territory_changes': 'TerritoryStatusBlockAndValues'
    }

    attribute_map = {
        'scenario_id': 'scenarioId',
        'pos_id': 'posId',
        'exclusive_zone_id': 'exclusiveZoneId',
        'is_implantation_block_exclusive': 'isImplantationBlockExclusive',
        'did_perform_update': 'didPerformUpdate',
        'conflicts': 'conflicts',
        'changes_to_other_territories': 'changesToOtherTerritories',
        'status': 'status',
        'pta_zone_id': 'ptaZoneId',
        'territory_changes': 'territoryChanges'
    }

    def __init__(self, scenario_id=None, pos_id=None, exclusive_zone_id=None, is_implantation_block_exclusive=None, did_perform_update=None, conflicts=None, changes_to_other_territories=None, status=None, pta_zone_id=None, territory_changes=None):  # noqa: E501
        """TerritoryStatusUpdateResponse - a model defined in Swagger"""  # noqa: E501
        self._scenario_id = None
        self._pos_id = None
        self._exclusive_zone_id = None
        self._is_implantation_block_exclusive = None
        self._did_perform_update = None
        self._conflicts = None
        self._changes_to_other_territories = None
        self._status = None
        self._pta_zone_id = None
        self._territory_changes = None
        self.discriminator = None
        if scenario_id is not None:
            self.scenario_id = scenario_id
        if pos_id is not None:
            self.pos_id = pos_id
        if exclusive_zone_id is not None:
            self.exclusive_zone_id = exclusive_zone_id
        if is_implantation_block_exclusive is not None:
            self.is_implantation_block_exclusive = is_implantation_block_exclusive
        if did_perform_update is not None:
            self.did_perform_update = did_perform_update
        if conflicts is not None:
            self.conflicts = conflicts
        if changes_to_other_territories is not None:
            self.changes_to_other_territories = changes_to_other_territories
        if status is not None:
            self.status = status
        if pta_zone_id is not None:
            self.pta_zone_id = pta_zone_id
        if territory_changes is not None:
            self.territory_changes = territory_changes

    @property
    def scenario_id(self):
        """Gets the scenario_id of this TerritoryStatusUpdateResponse.  # noqa: E501


        :return: The scenario_id of this TerritoryStatusUpdateResponse.  # noqa: E501
        :rtype: str
        """
        return self._scenario_id

    @scenario_id.setter
    def scenario_id(self, scenario_id):
        """Sets the scenario_id of this TerritoryStatusUpdateResponse.


        :param scenario_id: The scenario_id of this TerritoryStatusUpdateResponse.  # noqa: E501
        :type: str
        """

        self._scenario_id = scenario_id

    @property
    def pos_id(self):
        """Gets the pos_id of this TerritoryStatusUpdateResponse.  # noqa: E501


        :return: The pos_id of this TerritoryStatusUpdateResponse.  # noqa: E501
        :rtype: str
        """
        return self._pos_id

    @pos_id.setter
    def pos_id(self, pos_id):
        """Sets the pos_id of this TerritoryStatusUpdateResponse.


        :param pos_id: The pos_id of this TerritoryStatusUpdateResponse.  # noqa: E501
        :type: str
        """

        self._pos_id = pos_id

    @property
    def exclusive_zone_id(self):
        """Gets the exclusive_zone_id of this TerritoryStatusUpdateResponse.  # noqa: E501


        :return: The exclusive_zone_id of this TerritoryStatusUpdateResponse.  # noqa: E501
        :rtype: int
        """
        return self._exclusive_zone_id

    @exclusive_zone_id.setter
    def exclusive_zone_id(self, exclusive_zone_id):
        """Sets the exclusive_zone_id of this TerritoryStatusUpdateResponse.


        :param exclusive_zone_id: The exclusive_zone_id of this TerritoryStatusUpdateResponse.  # noqa: E501
        :type: int
        """

        self._exclusive_zone_id = exclusive_zone_id

    @property
    def is_implantation_block_exclusive(self):
        """Gets the is_implantation_block_exclusive of this TerritoryStatusUpdateResponse.  # noqa: E501


        :return: The is_implantation_block_exclusive of this TerritoryStatusUpdateResponse.  # noqa: E501
        :rtype: bool
        """
        return self._is_implantation_block_exclusive

    @is_implantation_block_exclusive.setter
    def is_implantation_block_exclusive(self, is_implantation_block_exclusive):
        """Sets the is_implantation_block_exclusive of this TerritoryStatusUpdateResponse.


        :param is_implantation_block_exclusive: The is_implantation_block_exclusive of this TerritoryStatusUpdateResponse.  # noqa: E501
        :type: bool
        """

        self._is_implantation_block_exclusive = is_implantation_block_exclusive

    @property
    def did_perform_update(self):
        """Gets the did_perform_update of this TerritoryStatusUpdateResponse.  # noqa: E501


        :return: The did_perform_update of this TerritoryStatusUpdateResponse.  # noqa: E501
        :rtype: bool
        """
        return self._did_perform_update

    @did_perform_update.setter
    def did_perform_update(self, did_perform_update):
        """Sets the did_perform_update of this TerritoryStatusUpdateResponse.


        :param did_perform_update: The did_perform_update of this TerritoryStatusUpdateResponse.  # noqa: E501
        :type: bool
        """

        self._did_perform_update = did_perform_update

    @property
    def conflicts(self):
        """Gets the conflicts of this TerritoryStatusUpdateResponse.  # noqa: E501


        :return: The conflicts of this TerritoryStatusUpdateResponse.  # noqa: E501
        :rtype: TerritoryUpdateConflicts
        """
        return self._conflicts

    @conflicts.setter
    def conflicts(self, conflicts):
        """Sets the conflicts of this TerritoryStatusUpdateResponse.


        :param conflicts: The conflicts of this TerritoryStatusUpdateResponse.  # noqa: E501
        :type: TerritoryUpdateConflicts
        """

        self._conflicts = conflicts

    @property
    def changes_to_other_territories(self):
        """Gets the changes_to_other_territories of this TerritoryStatusUpdateResponse.  # noqa: E501


        :return: The changes_to_other_territories of this TerritoryStatusUpdateResponse.  # noqa: E501
        :rtype: ChangesToTerritories
        """
        return self._changes_to_other_territories

    @changes_to_other_territories.setter
    def changes_to_other_territories(self, changes_to_other_territories):
        """Sets the changes_to_other_territories of this TerritoryStatusUpdateResponse.


        :param changes_to_other_territories: The changes_to_other_territories of this TerritoryStatusUpdateResponse.  # noqa: E501
        :type: ChangesToTerritories
        """

        self._changes_to_other_territories = changes_to_other_territories

    @property
    def status(self):
        """Gets the status of this TerritoryStatusUpdateResponse.  # noqa: E501


        :return: The status of this TerritoryStatusUpdateResponse.  # noqa: E501
        :rtype: TerritoryStatusEnum
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this TerritoryStatusUpdateResponse.


        :param status: The status of this TerritoryStatusUpdateResponse.  # noqa: E501
        :type: TerritoryStatusEnum
        """

        self._status = status

    @property
    def pta_zone_id(self):
        """Gets the pta_zone_id of this TerritoryStatusUpdateResponse.  # noqa: E501


        :return: The pta_zone_id of this TerritoryStatusUpdateResponse.  # noqa: E501
        :rtype: int
        """
        return self._pta_zone_id

    @pta_zone_id.setter
    def pta_zone_id(self, pta_zone_id):
        """Sets the pta_zone_id of this TerritoryStatusUpdateResponse.


        :param pta_zone_id: The pta_zone_id of this TerritoryStatusUpdateResponse.  # noqa: E501
        :type: int
        """

        self._pta_zone_id = pta_zone_id

    @property
    def territory_changes(self):
        """Gets the territory_changes of this TerritoryStatusUpdateResponse.  # noqa: E501


        :return: The territory_changes of this TerritoryStatusUpdateResponse.  # noqa: E501
        :rtype: TerritoryStatusBlockAndValues
        """
        return self._territory_changes

    @territory_changes.setter
    def territory_changes(self, territory_changes):
        """Sets the territory_changes of this TerritoryStatusUpdateResponse.


        :param territory_changes: The territory_changes of this TerritoryStatusUpdateResponse.  # noqa: E501
        :type: TerritoryStatusBlockAndValues
        """

        self._territory_changes = territory_changes

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TerritoryStatusUpdateResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TerritoryStatusUpdateResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
