# coding: utf-8

"""
    CartoVista REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class UpdateTerritoryPosStatusParameter(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'acknowledged_implantation_conflicts': 'bool',
        'resolutions': 'OneOfUpdateTerritoryPosStatusParameterResolutions',
        'status': 'TerritoryStatusEnum'
    }

    attribute_map = {
        'acknowledged_implantation_conflicts': 'acknowledgedImplantationConflicts',
        'resolutions': 'resolutions',
        'status': 'status'
    }

    def __init__(self, acknowledged_implantation_conflicts=None, resolutions=None, status=None):  # noqa: E501
        """UpdateTerritoryPosStatusParameter - a model defined in Swagger"""  # noqa: E501
        self._acknowledged_implantation_conflicts = None
        self._resolutions = None
        self._status = None
        self.discriminator = None
        if acknowledged_implantation_conflicts is not None:
            self.acknowledged_implantation_conflicts = acknowledged_implantation_conflicts
        if resolutions is not None:
            self.resolutions = resolutions
        if status is not None:
            self.status = status

    @property
    def acknowledged_implantation_conflicts(self):
        """Gets the acknowledged_implantation_conflicts of this UpdateTerritoryPosStatusParameter.  # noqa: E501


        :return: The acknowledged_implantation_conflicts of this UpdateTerritoryPosStatusParameter.  # noqa: E501
        :rtype: bool
        """
        return self._acknowledged_implantation_conflicts

    @acknowledged_implantation_conflicts.setter
    def acknowledged_implantation_conflicts(self, acknowledged_implantation_conflicts):
        """Sets the acknowledged_implantation_conflicts of this UpdateTerritoryPosStatusParameter.


        :param acknowledged_implantation_conflicts: The acknowledged_implantation_conflicts of this UpdateTerritoryPosStatusParameter.  # noqa: E501
        :type: bool
        """

        self._acknowledged_implantation_conflicts = acknowledged_implantation_conflicts

    @property
    def resolutions(self):
        """Gets the resolutions of this UpdateTerritoryPosStatusParameter.  # noqa: E501


        :return: The resolutions of this UpdateTerritoryPosStatusParameter.  # noqa: E501
        :rtype: OneOfUpdateTerritoryPosStatusParameterResolutions
        """
        return self._resolutions

    @resolutions.setter
    def resolutions(self, resolutions):
        """Sets the resolutions of this UpdateTerritoryPosStatusParameter.


        :param resolutions: The resolutions of this UpdateTerritoryPosStatusParameter.  # noqa: E501
        :type: OneOfUpdateTerritoryPosStatusParameterResolutions
        """

        self._resolutions = resolutions

    @property
    def status(self):
        """Gets the status of this UpdateTerritoryPosStatusParameter.  # noqa: E501


        :return: The status of this UpdateTerritoryPosStatusParameter.  # noqa: E501
        :rtype: TerritoryStatusEnum
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this UpdateTerritoryPosStatusParameter.


        :param status: The status of this UpdateTerritoryPosStatusParameter.  # noqa: E501
        :type: TerritoryStatusEnum
        """

        self._status = status

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(UpdateTerritoryPosStatusParameter, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UpdateTerritoryPosStatusParameter):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
