# coding: utf-8

"""
    CartoVista REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import cartovista_cloud_clients
from cartovista_cloud_clients.api.grid_layer_settings_api import GridLayerSettingsApi  # noqa: E501
from cartovista_cloud_clients.rest import ApiException


class TestGridLayerSettingsApi(unittest.TestCase):
    """GridLayerSettingsApi unit test stubs"""

    def setUp(self):
        self.api = GridLayerSettingsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_grid_layer_settings_get_default_grid_layer_settings(self):
        """Test case for grid_layer_settings_get_default_grid_layer_settings

        Gets the default settings for the grid layer.  # noqa: E501
        """
        pass

    def test_grid_layer_settings_get_grid_layer_settings(self):
        """Test case for grid_layer_settings_get_grid_layer_settings

        Gets a specific grid layer settings.  # noqa: E501
        """
        pass

    def test_grid_layer_settings_get_map_grid_layer_settings(self):
        """Test case for grid_layer_settings_get_map_grid_layer_settings

        Gets the grid layer's settings for a specific map.  # noqa: E501
        """
        pass

    def test_grid_layer_settings_update_alias(self):
        """Test case for grid_layer_settings_update_alias

        Updates the grid layer settings' alias.  # noqa: E501
        """
        pass

    def test_grid_layer_settings_update_rendering(self):
        """Test case for grid_layer_settings_update_rendering

        Updates the grid layer settings' rendering settings.  # noqa: E501
        """
        pass

    def test_grid_layer_settings_update_style(self):
        """Test case for grid_layer_settings_update_style

        Updates the grid layer settings' style.  # noqa: E501
        """
        pass

    def test_grid_layer_settings_update_visibility_ranges(self):
        """Test case for grid_layer_settings_update_visibility_ranges

        Updates the grid layer settings' visibility ranges.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
