# coding: utf-8

"""
    CartoVista REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import cartovista_cloud_clients
from cartovista_cloud_clients.api.wmts_api import WmtsApi  # noqa: E501
from cartovista_cloud_clients.rest import ApiException


class TestWmtsApi(unittest.TestCase):
    """WmtsApi unit test stubs"""

    def setUp(self):
        self.api = WmtsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_wmts_create_wmts_layer(self):
        """Test case for wmts_create_wmts_layer

        Creates a new WMTS layer.  # noqa: E501
        """
        pass

    def test_wmts_delete_wmts_layer(self):
        """Test case for wmts_delete_wmts_layer

        Deletes the WMTS layer.  # noqa: E501
        """
        pass

    def test_wmts_get_wmts_layer(self):
        """Test case for wmts_get_wmts_layer

        Gets a specific WMTs layer.  # noqa: E501
        """
        pass

    def test_wmts_get_wmts_layer_details(self):
        """Test case for wmts_get_wmts_layer_details

        Gets the WMTS layer and its related maps.  # noqa: E501
        """
        pass

    def test_wmts_get_wmts_layers(self):
        """Test case for wmts_get_wmts_layers

        Gets all the WMTS layers the user has access to.  # noqa: E501
        """
        pass

    def test_wmts_update_wmts_layer(self):
        """Test case for wmts_update_wmts_layer

        Updates the WMTS layer's properties.  # noqa: E501
        """
        pass

    def test_wmts_update_wmts_layer_permissions(self):
        """Test case for wmts_update_wmts_layer_permissions

        Updates the WMTS layer's permissions.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
