# coding: utf-8

"""
    CartoVista REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import cartovista_cloud_clients
from cartovista_cloud_clients.api.composite_variable_scoring_api import CompositeVariableScoringApi  # noqa: E501
from cartovista_cloud_clients.rest import ApiException


class TestCompositeVariableScoringApi(unittest.TestCase):
    """CompositeVariableScoringApi unit test stubs"""

    def setUp(self):
        self.api = CompositeVariableScoringApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_composite_variable_scoring_can_modify_analyses(self):
        """Test case for composite_variable_scoring_can_modify_analyses

        Checks whether or not the current user can modify the analyses of the given map.  # noqa: E501
        """
        pass

    def test_composite_variable_scoring_create_composite_scoring_analysis(self):
        """Test case for composite_variable_scoring_create_composite_scoring_analysis

        Creates a scoring analysis for a map and a layer.  # noqa: E501
        """
        pass

    def test_composite_variable_scoring_create_variable(self):
        """Test case for composite_variable_scoring_create_variable

        Creates a variable for a given analysis. The scores are recomputed.  # noqa: E501
        """
        pass

    def test_composite_variable_scoring_delete_analysis(self):
        """Test case for composite_variable_scoring_delete_analysis

        Deletes an analysis. The scores are recomputed  # noqa: E501
        """
        pass

    def test_composite_variable_scoring_delete_variable(self):
        """Test case for composite_variable_scoring_delete_variable

        Deletes a variable. The scores are recomputed  # noqa: E501
        """
        pass

    def test_composite_variable_scoring_get_all_composite_scoring_analysis(self):
        """Test case for composite_variable_scoring_get_all_composite_scoring_analysis

        Gets all the analyses associated to a map.  # noqa: E501
        """
        pass

    def test_composite_variable_scoring_get_composite_scoring_analysis_data_table(self):
        """Test case for composite_variable_scoring_get_composite_scoring_analysis_data_table

        Gets a summary of the score column and how it is joined to the existing data.  # noqa: E501
        """
        pass

    def test_composite_variable_scoring_get_variable(self):
        """Test case for composite_variable_scoring_get_variable

        Gets a specific variable.  # noqa: E501
        """
        pass

    def test_composite_variable_scoring_get_variables(self):
        """Test case for composite_variable_scoring_get_variables

        Gets the variables for a specific analysis.  # noqa: E501
        """
        pass

    def test_composite_variable_scoring_update_analysis_properties(self):
        """Test case for composite_variable_scoring_update_analysis_properties

        Updates a variable. The scores are recomputed.  # noqa: E501
        """
        pass

    def test_composite_variable_scoring_update_variable(self):
        """Test case for composite_variable_scoring_update_variable

        Updates a variable. The scores are recomputed.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
