# coding: utf-8

"""
    CartoVista REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import cartovista_cloud_clients
from cartovista_cloud_clients.models.grid_layer_settings_style_mode import GridLayerSettingsStyleMode  # noqa: E501
from cartovista_cloud_clients.rest import ApiException


class TestGridLayerSettingsStyleMode(unittest.TestCase):
    """GridLayerSettingsStyleMode unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGridLayerSettingsStyleMode(self):
        """Test GridLayerSettingsStyleMode"""
        # FIXME: construct object with mandatory attributes with example values
        # model = cartovista_cloud_clients.models.grid_layer_settings_style_mode.GridLayerSettingsStyleMode()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
