# coding: utf-8

"""
    CartoVista REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import cartovista_cloud_clients
from cartovista_cloud_clients.api.wms_settings_api import WmsSettingsApi  # noqa: E501
from cartovista_cloud_clients.rest import ApiException


class TestWmsSettingsApi(unittest.TestCase):
    """WmsSettingsApi unit test stubs"""

    def setUp(self):
        self.api = WmsSettingsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_wms_settings_get_wms_settings(self):
        """Test case for wms_settings_get_wms_settings

        Gets the WMS settings.  # noqa: E501
        """
        pass

    def test_wms_settings_update_wms_settings(self):
        """Test case for wms_settings_update_wms_settings

        Updates the WMS settings.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
