# coding: utf-8

"""
    CartoVista REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import cartovista_cloud_clients
from cartovista_cloud_clients.api.api_key_api import ApiKeyApi  # noqa: E501
from cartovista_cloud_clients.rest import ApiException


class TestApiKeyApi(unittest.TestCase):
    """ApiKeyApi unit test stubs"""

    def setUp(self):
        self.api = ApiKeyApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_key_create_access_key(self):
        """Test case for api_key_create_access_key

        Generates an access key for a specific user.  # noqa: E501
        """
        pass

    def test_api_key_delete_api_key(self):
        """Test case for api_key_delete_api_key

        Deletes an API key.  # noqa: E501
        """
        pass

    def test_api_key_generate_secret_key(self):
        """Test case for api_key_generate_secret_key

        Generates a secret key for additional security on the access key.  # noqa: E501
        """
        pass

    def test_api_key_get_access_keys(self):
        """Test case for api_key_get_access_keys

        Gets all the access keys created for a specific user.  # noqa: E501
        """
        pass

    def test_api_key_update_access_key(self):
        """Test case for api_key_update_access_key

        Updates the access key.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
