# coding: utf-8

"""
    CartoVista REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import cartovista_cloud_clients
from cartovista_cloud_clients.models.one_of_individual_values_on_multiple_columns_message_dtoof_data_query_column_dto_spatial_filter import OneOfIndividualValuesOnMultipleColumnsMessageDTOOfDataQueryColumnDTOSpatialFilter  # noqa: E501
from cartovista_cloud_clients.rest import ApiException
from generated_test_utils import build_model_instance


class TestOneOfIndividualValuesOnMultipleColumnsMessageDTOOfDataQueryColumnDTOSpatialFilter(unittest.TestCase):
    """OneOfIndividualValuesOnMultipleColumnsMessageDTOOfDataQueryColumnDTOSpatialFilter unit test stubs"""

    def setUp(self):
        self.model_class = OneOfIndividualValuesOnMultipleColumnsMessageDTOOfDataQueryColumnDTOSpatialFilter

    def tearDown(self):
        self.model_class = None

    def testOneOfIndividualValuesOnMultipleColumnsMessageDTOOfDataQueryColumnDTOSpatialFilter(self):
        """Test OneOfIndividualValuesOnMultipleColumnsMessageDTOOfDataQueryColumnDTOSpatialFilter"""
        model = build_model_instance(self.model_class)
        self.assertIsInstance(model, self.model_class)
        self.assertEqual(set(model.swagger_types), set(model.to_dict()))
        self.assertEqual(model.to_str(), repr(model))
        self.assertEqual(model, build_model_instance(self.model_class))


if __name__ == '__main__':
    unittest.main()
