# coding: utf-8

"""
    CartoVista REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import cartovista_cloud_clients
from cartovista_cloud_clients.api.file_api import FileApi  # noqa: E501
from cartovista_cloud_clients.rest import ApiException


class TestFileApi(unittest.TestCase):
    """FileApi unit test stubs"""

    def setUp(self):
        self.api = FileApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_file_download_file(self):
        """Test case for file_download_file

        Downloads the data.  # noqa: E501
        """
        pass

    def test_file_download_grid_source(self):
        """Test case for file_download_grid_source

        Downloads the grid source in the given grid layer.  # noqa: E501
        """
        pass

    def test_file_download_series(self):
        """Test case for file_download_series

        """
        pass

    def test_file_export_feedback(self):
        """Test case for file_export_feedback

        Exports the map's feedback in MapInfo format.  # noqa: E501
        """
        pass

    def test_file_get_custom_poi_analysis_post_project_heatmap(self):
        """Test case for file_get_custom_poi_analysis_post_project_heatmap

        """
        pass

    def test_file_get_custom_poi_analysis_worst_dispatch_heatmap(self):
        """Test case for file_get_custom_poi_analysis_worst_dispatch_heatmap

        """
        pass

    def test_file_get_data(self):
        """Test case for file_get_data

        Gets a chunk of the grid layer's data.  # noqa: E501
        """
        pass

    def test_file_get_poi_analysis_heatmap(self):
        """Test case for file_get_poi_analysis_heatmap

        """
        pass

    def test_file_get_raster(self):
        """Test case for file_get_raster

        Generates a WMS raster in PNG format.  # noqa: E501
        """
        pass

    def test_file_get_symbol_file(self):
        """Test case for file_get_symbol_file

        Downloads the symbol's file.  # noqa: E501
        """
        pass

    def test_file_get_tile(self):
        """Test case for file_get_tile

        """
        pass


if __name__ == '__main__':
    unittest.main()
