# coding: utf-8

"""
    CartoVista REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import cartovista_cloud_clients
from cartovista_cloud_clients.models.joined_editable_data_row import JoinedEditableDataRow  # noqa: E501
from cartovista_cloud_clients.rest import ApiException


class TestJoinedEditableDataRow(unittest.TestCase):
    """JoinedEditableDataRow unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testJoinedEditableDataRow(self):
        """Test JoinedEditableDataRow"""
        # FIXME: construct object with mandatory attributes with example values
        # model = cartovista_cloud_clients.models.joined_editable_data_row.JoinedEditableDataRow()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
