# coding: utf-8

"""
    CartoVista REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import cartovista_cloud_clients
from cartovista_cloud_clients.models.analyze_distances_parameter import AnalyzeDistancesParameter  # noqa: E501
from cartovista_cloud_clients.rest import ApiException


class TestAnalyzeDistancesParameter(unittest.TestCase):
    """AnalyzeDistancesParameter unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAnalyzeDistancesParameter(self):
        """Test AnalyzeDistancesParameter"""
        # FIXME: construct object with mandatory attributes with example values
        # model = cartovista_cloud_clients.models.analyze_distances_parameter.AnalyzeDistancesParameter()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
