# coding: utf-8

"""
    CartoVista REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import cartovista_cloud_clients
from cartovista_cloud_clients.api.vector_services_api import VectorServicesApi  # noqa: E501
from cartovista_cloud_clients.rest import ApiException


class TestVectorServicesApi(unittest.TestCase):
    """VectorServicesApi unit test stubs"""

    def setUp(self):
        self.api = VectorServicesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_vector_services_get_clusters_count(self):
        """Test case for vector_services_get_clusters_count

        """
        pass

    def test_vector_services_get_clusters_representation(self):
        """Test case for vector_services_get_clusters_representation

        """
        pass

    def test_vector_services_get_configuration(self):
        """Test case for vector_services_get_configuration

        """
        pass

    def test_vector_services_get_features(self):
        """Test case for vector_services_get_features

        """
        pass

    def test_vector_services_get_features_combine_min_max_value(self):
        """Test case for vector_services_get_features_combine_min_max_value

        """
        pass

    def test_vector_services_get_features_extent(self):
        """Test case for vector_services_get_features_extent

        """
        pass

    def test_vector_services_get_heat_map_items(self):
        """Test case for vector_services_get_heat_map_items

        """
        pass

    def test_vector_services_get_intersecting_geometries(self):
        """Test case for vector_services_get_intersecting_geometries

        """
        pass

    def test_vector_services_get_selection_stack(self):
        """Test case for vector_services_get_selection_stack

        """
        pass

    def test_vector_services_get_vector_tile(self):
        """Test case for vector_services_get_vector_tile

        """
        pass


if __name__ == '__main__':
    unittest.main()
