# coding: utf-8

"""
    CartoVista REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import cartovista_cloud_clients
from cartovista_cloud_clients.api.data_services_api import DataServicesApi  # noqa: E501
from cartovista_cloud_clients.rest import ApiException


class TestDataServicesApi(unittest.TestCase):
    """DataServicesApi unit test stubs"""

    def setUp(self):
        self.api = DataServicesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_data_services_data_query_execute(self):
        """Test case for data_services_data_query_execute

        """
        pass

    def test_data_services_get_feature_count_equal_to_classifications(self):
        """Test case for data_services_get_feature_count_equal_to_classifications

        """
        pass

    def test_data_services_get_feature_count_equal_to_value(self):
        """Test case for data_services_get_feature_count_equal_to_value

        """
        pass

    def test_data_services_get_feature_count_in_range_of_value(self):
        """Test case for data_services_get_feature_count_in_range_of_value

        """
        pass

    def test_data_services_get_feature_count_out_of_range(self):
        """Test case for data_services_get_feature_count_out_of_range

        """
        pass

    def test_data_services_get_individual_values(self):
        """Test case for data_services_get_individual_values

        """
        pass

    def test_data_services_get_individual_values_on_multiple_columns(self):
        """Test case for data_services_get_individual_values_on_multiple_columns

        """
        pass

    def test_data_services_get_linking_id_index(self):
        """Test case for data_services_get_linking_id_index

        """
        pass

    def test_data_services_get_ranges(self):
        """Test case for data_services_get_ranges

        """
        pass


if __name__ == '__main__':
    unittest.main()
