# coding: utf-8

"""
    CartoVista REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import cartovista_cloud_clients
from cartovista_cloud_clients.api.authentication_api import AuthenticationApi  # noqa: E501
from cartovista_cloud_clients.rest import ApiException


class TestAuthenticationApi(unittest.TestCase):
    """AuthenticationApi unit test stubs"""

    def setUp(self):
        self.api = AuthenticationApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_authentication_global_login(self):
        """Test case for authentication_global_login

        """
        pass

    def test_authentication_logout(self):
        """Test case for authentication_logout

        """
        pass

    def test_authentication_request_new_token(self):
        """Test case for authentication_request_new_token

        """
        pass

    def test_authentication_request_password_reset(self):
        """Test case for authentication_request_password_reset

        """
        pass

    def test_authentication_reset_password(self):
        """Test case for authentication_reset_password

        """
        pass

    def test_authentication_set_external_provider(self):
        """Test case for authentication_set_external_provider

        """
        pass

    def test_authentication_tenant_login(self):
        """Test case for authentication_tenant_login

        """
        pass

    def test_authentication_validate_reset_code(self):
        """Test case for authentication_validate_reset_code

        """
        pass


if __name__ == '__main__':
    unittest.main()
