# coding: utf-8

"""
    CartoVista REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import cartovista_cloud_clients
from cartovista_cloud_clients.models.get_feature_count_in_range_of_message_dtoof_data_query_column_dto import GetFeatureCountInRangeOfMessageDTOOfDataQueryColumnDTO  # noqa: E501
from cartovista_cloud_clients.rest import ApiException


class TestGetFeatureCountInRangeOfMessageDTOOfDataQueryColumnDTO(unittest.TestCase):
    """GetFeatureCountInRangeOfMessageDTOOfDataQueryColumnDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetFeatureCountInRangeOfMessageDTOOfDataQueryColumnDTO(self):
        """Test GetFeatureCountInRangeOfMessageDTOOfDataQueryColumnDTO"""
        # FIXME: construct object with mandatory attributes with example values
        # model = cartovista_cloud_clients.models.get_feature_count_in_range_of_message_dtoof_data_query_column_dto.GetFeatureCountInRangeOfMessageDTOOfDataQueryColumnDTO()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
