# coding: utf-8

"""
    CartoVista REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import cartovista_cloud_clients
from cartovista_cloud_clients.models.one_of_get_clusters_representation_dtoof_data_query_column_dto_out_of_range_value import OneOfGetClustersRepresentationDTOOfDataQueryColumnDTOOutOfRangeValue  # noqa: E501
from cartovista_cloud_clients.rest import ApiException


class TestOneOfGetClustersRepresentationDTOOfDataQueryColumnDTOOutOfRangeValue(unittest.TestCase):
    """OneOfGetClustersRepresentationDTOOfDataQueryColumnDTOOutOfRangeValue unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOneOfGetClustersRepresentationDTOOfDataQueryColumnDTOOutOfRangeValue(self):
        """Test OneOfGetClustersRepresentationDTOOfDataQueryColumnDTOOutOfRangeValue"""
        # FIXME: construct object with mandatory attributes with example values
        # model = cartovista_cloud_clients.models.one_of_get_clusters_representation_dtoof_data_query_column_dto_out_of_range_value.OneOfGetClustersRepresentationDTOOfDataQueryColumnDTOOutOfRangeValue()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
